app/import_transactions/__init__.py
from flask import Blueprint

blueprint = Blueprint(
    'import_transactions_blueprint',
    __name__,
    url_prefix='/import_transactions',
    template_folder='templates',
    static_folder='static'
)



app/import_transactions/routes.py
from . import blueprint
from flask import Flask, render_template, session, redirect, url_for, session, request, current_app
from flask_wtf import FlaskForm
from flask_login import login_required, current_user
from wtforms import (SelectField,StringField,
                     SubmitField, DecimalField, DateField)

from wtforms.fields.html5 import DateField
from transaction import Buy, Sell
import json
from werkzeug.utils import secure_filename
from flask import jsonify
from conversion import Conversion

from wtforms.fields.html5 import DateTimeLocalField
from utils import *

import dateutil.parser

class ManualTransaction(FlaskForm):
    '''
    Manual Transaction values
    '''
    timestamp = DateTimeLocalField('Timestamp', format='%Y-%m-%dT%H:%M')
    type  = SelectField(u'Type', choices=[('buy', 'Buy'), ('sell', 'Sell')])
    symbol = StringField('Crypto Symbol')
    quantity = DecimalField('Quantity', rounding=None)
    usd_spot = DecimalField('USD Spot', rounding=None)

    submit = SubmitField('Submit')


class CurrentHodl(FlaskForm):
    symbol = StringField('Crypto Symbol')
    quantity = DecimalField('Quantity', rounding=None)
    
    submit = SubmitField('Submit')


@blueprint.route('/', methods=['GET', 'POST'])
@login_required
def import_wizard():

    transactions = current_app.config['transactions']
    manual_trans = ManualTransaction()
    current_hodl = CurrentHodl()

    if 'current_hodl' not in session:
        session['current_hodl'] = []

    # if file is uploaded add new transactions 
    if request.method == 'POST':

        # Import from CSV File
        if 'file' in request.files:
            file = request.files['file']
            transactions.import_transactions(file, filename=secure_filename(file.filename))
    

        # Current Hodl
        if current_hodl.validate_on_submit():
           pass

    
    stats_table_data = get_stats_table_data(transactions)
    all_trans_table_data = get_all_trans_table_data(transactions)
    
    return render_template('import_transactions.html', manual_trans=manual_trans, current_hodl=current_hodl,transactions=all_trans_table_data, stats_table_data=stats_table_data)



app/import_transactions/templates/import_transactions.html
{% extends "base_site.html" %}

{% block title %} Import Transactions {% endblock title %}

{% block stylesheets %}
  {{ super() }}
{% endblock stylesheets %}

{% block content %}


<!-- Page Description and Instructions -->
<div class="row">
  <div class="col-md-12">
    <div class="card">
      <div class="card-body">
        <div id="accordion" role="tablist" aria-multiselectable="true" class="card-collapse">
          <h4 class="card-title">Step 1: Import CSV's from exchange</h4>
          <div class="card card-plain">
            <div class="card-header" role="tab" id="headingOne">
              <a data-toggle="collapse" data-parent="#accordion" href="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
                How to use this page
                <i class="nc-icon nc-minimal-down"></i>
              </a>
            </div>
            <div id="collapseOne" class="collapse show" role="tabpanel" aria-labelledby="headingOne">
              <div class="card-body">
                Drag and Drop exchange CSV's into the upload area below. Currently Coinbase and Cashapp formats are supported. 
                <br> Transaction type of Convert will be imported as a sell @ USD Spot price at transaction and a buy @ USD Total (inclusive of fees)
                <br> Open CMD for progress on Coinbase Pro Imports as it may take a while to lookup prices from coinbase API. 
                <br> keep coinbase, coinbase pro, kraken, in the filename respecitvly for identification. 
                <br><br>
                Upload one file at a time.
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<!-- /Page Description and Instructions -->
      

<!-- Upload -->
<div class="row">
  <div class="col-md-12">
    <div class="card">
      <div class="card-body">
        <form id="upload_csv_form" action="{{ url_for('import_transactions_blueprint.import_wizard')}}" class="dropzone"></form>
      </div>
    </div>
  </div>
</div>
<!-- /Upload  -->




{% endblock content %}

{% block javascripts %}
  {{ super()}}
{% endblock javascripts %}


